baseURL = ""
languageCode = "en-us"
title = "BoredGuyWrites"
theme = "simplish"
summaryLength = 50

[pagination]
  pagerSize = 6  # Number of posts per page

[params]
  description = "A blog about travel, tech, food, and life."
  year = 2025

canonifyURLs = true

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "static"
    target = "assets"