baseURL = "https://example.com/"
languageCode = "en-us"
title = "BoredGuyWrites"
theme = "simplish"
summaryLength = 50

[pagination]
pagerSize = 6  # Change this to the number of posts per page

[params]
  description = "A blog about travel, tech, food, and life."
  year = 2025